/* Attribution des privilèges objets pour l'utilisateur 2 (utilisateur web) */

--Package
GRANT EXECUTE ON packageScore TO SCT2985A;

--Procédures
GRANT EXECUTE ON inserer_joueur TO SCT2985A;
GRANT EXECUTE ON update_joueur TO SCT2985A;
GRANT EXECUTE ON inserer_partie TO SCT2985A;
GRANT EXECUTE ON inserer_historique TO SCT2985A;
GRANT EXECUTE ON fin_partie TO SCT2985A;
GRANT EXECUTE ON etat_null TO SCT2985A;

--Tables
GRANT SELECT ON JOUEUR TO SCT2985A;
GRANT SELECT ON PARTIE TO SCT2985A;
GRANT SELECT ON FIGURE TO SCT2985A;
GRANT SELECT ON NIVEAU TO SCT2985A;
GRANT SELECT ON HISTORIQUE TO SCT2985A;
GRANT SELECT ON REPRESENTATION TO SCT2985A;
GRANT SELECT ON ACTION TO SCT2985A;

